FROM jk-spark-cluster/spark-base


COPY master.sh /
COPY history-server.sh /

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /spark/logs
ENV SPARK_HISTORY_SERVER_LOG /spark/history-server/logs
ENV SPARK_MASTER_HOST spark-master

EXPOSE 18080 18081

CMD ["/bin/bash", "/history-server.sh"]