version: '3'
services:
    jupyter-pyspark-notebook:
        image: jupyter/pyspark-notebook
        container_name: jupyter-pyspark-notebook
        # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html
        ports:
        - "8888:8888"
        - "4040:4040"
        - "4041:4041"
        - "4042:4042"
        - "4043:4043"
        - "4044:4044"
        - "4045:4045"
        volumes:
            - ./my_notebooks:/work
